/**
 * @param {import("knex").Knex} knex
 * @returns {Promise<void>}
 */
export async function up(knex) {
    return knex.schema.createTable("spreadsheets", (table) => {
        table.specificType("id", "bigint GENERATED BY DEFAULT AS IDENTITY").primary();
        table.string("warehouse_name").notNullable().comment("Название склада");
        table.string("geo_name").notNullable().comment("Географическое название");
        table.string("box_delivery_base").notNullable().comment("Базовая стоимость доставки коробки");
        table.string("box_delivery_coef_expr").notNullable().comment("Коэффициент выражения доставки коробки");
        table.string("box_delivery_liter").notNullable().comment("Литровая стоимость доставки коробки");
        table.string("box_delivery_marketplace_base").notNullable().comment("Базовая стоимость доставки коробки на маркетплейс");
        table.string("box_delivery_marketplace_coef_expr").notNullable().comment("Коэффициент выражения доставки коробки на маркетплейс");
        table.string("box_delivery_marketplace_liter").notNullable().comment("Литровая стоимость доставки коробки на маркетплейс");
        table.string("box_storage_base").notNullable().comment("Базовая стоимость хранения коробки");
        table.string("box_storage_coef_expr").notNullable().comment("Коэффициент выражения хранения коробки");
        table.string("box_storage_liter").notNullable().comment("Литровая стоимость хранения коробки");
        table.date("fetch_date").notNullable().comment("Дата получения данных");
        //table.timestamps(true, true);

        //table.primary(["warehouse_name", "fetch_date"]);
    });
}

/**
 * @param {import("knex").Knex} knex
 * @returns {Promise<void>}
 */
export async function down(knex) {
    return knex.schema.dropTable("spreadsheets");
}
